### PR TITLE
more tested devices and new types switch and energie

### PR DESCRIPTION
**Pull request by spitzlbergerj**
Hello, Sebastian,
I tested a few more devices and installed the type switch. I also made a correction in the window contacts, because my Homematic Sensor doesn't output numeric values, but a boolean one.

And another question: You write below that the update interval depends on Forecast.io and therefore should not be set too low. Is that still relevant? I couldn't find a reference to Forecast.io in the COde ....

Maybe you want to include the extension in your code again.

many greetings
Sepp

### CODE REVIEW

**Comment by Sickboy78** [comment]
Hi Sepp,

great work!
I try to find time on the weekend to have a look and merge it.

Best Regards
Sebastian

**Comment by spitzlbergerj** [comment]
Hello, Sebastian,
 I would like to add another change this weekend.  The energy values don't have a unit at the end yet. I would like to do that. But I won't be able to do it until Sunday at the earliest. Of course, if you feel like it, then you can install it yourself. Just let me know that it's already your turn.
Many greetings

Sepp

**Comment by spitzlbergerj** [comment]
Hello, Sebastian,
I was now able to install and test the new code. It all works. So you can check and then merge if you like

**Comment by spitzlbergerj** [comment]
Hello, Sebastian,
I wanted to add .toLocaleString('de-DE') to display commas and thousands of points at other and energie (but also at temp and hum). Unfortunately this doesn't work for me and I can't find the error. Maybe you have another idea ...

I have tried e.g. with the energy:
let valueStr = Number(value).toFixed(this.precision).toLocaleString('de-DE');

But that doesn't return a comma or a thousand point.

Many greetings

Sepp

**Comment by Sickboy78** [comment]
Hi Sepp,

looks great, I have merged it.
As for your question:
Both toLocaleString and toFixed take a Number and return a String, so you can't combine them.
But fortunately there is a way, as the toLocaleString methode accepts a second parameter with options.
So what you want to achieve, can be done with:

`Number(value).toLocaleString('de-DE', {minimumFractionDigits: this.precision, maximumFractionDigits: this.precision});`

Best Regards
Sebastian

**Comment by Sickboy78** [comment]
Hi Sepp,

I cant find the mentioned reference to forecast.io.
But in case I missed it, you can remove it. I just used the forecast.io project as a template, perhaps I forgot to remove something there ...
_Edit: Just saw, you already removed it._ 

Best Regards
Sebastian

**Comment by spitzlbergerj** [comment]
Hi Sebastian,
I thought so. It was a reference in the ReadMe that made a restriction in the update interval due to forecast.io. I took that out of my version and also adapted the unit of the interval to the code.

So this should fit now.

Could you solve the problem with the "German number format"?

Many greetings

Sepp

**Pull request merged**
