### PR TITLE
Introduction of table view

### PR DESCRIPTION
**Pull request by spitzlbergerj**
Hi Sickboy78,

I have introduced the possibility of a table view.
 
There is still a problem if warnOnly is set to true. Then the column for this element is displayed, but not the icon. Actually the whole column should not be displayed. Unfortunately I did not get the correct query for this.

Also, the code should probably be adjusted, because the iconPosition top doesn't make sense anymore.

Unfortunately I don't have the time to adjust this completely in the near future - sorry!

Regards
Josef

### CODE REVIEW

**Comment by Sickboy78** [comment]
Hi Josef,

I hope your are well!
I will look into it, when I find the time.

Thx and Cu
Sebastian

**Comment by spitzlbergerj** [comment]
Hello, Sebastian,

all is well . thank you

I had some time today. I discovered the problem. I'll sit down tomorrow and correct it. You don't have to do anything for now.

Best regards.

Sepp

**Comment by spitzlbergerj** [comment]
Hi, Sebastian,
now everything should work. I found the error and fixed it.

I left the option iconPosition top in the code, so that this version incl. table view remains compatible with the previous version.

I made some more screenshots and also added

Greetings
Sepp

**Comment by spitzlbergerj** [comment]
Hi, Sebastian,
I discovered and corrected a blemish in display this morning. In a table with warn classes the icon is now colored, but not the text
Regards
Josef

**Comment by spitzlbergerj** [comment]
Hi, Sebastian,

i have now added the possibility to use icons from font awesome.

Many greetings 

Sepp

**Comment by Sickboy78** [comment]
Merged into dev branch instead of master, since there is a bug in table view, if no icon is set.
And I wamt todo some general improvements to the existing rendering code.

**Comment by spitzlbergerj** [comment]
oh, sorry about the bug. i'll take a look at it, but i'm pretty hot on the job because of corona. So this may take a while.

**Comment by Sickboy78** [comment]
Hi Josef!

No problem, I fixed the minor bug and I merged the new features into the master branch. I really like the table view, so much, I added a second one. :)
You can now choose between table_rows and table_columns. Table_columns is your table, where one datapoint is viewed in one column (vertical). And table_rows is the new one, where one datapoint is viewed in one row (horizontal).
As mentioned before, I also did a refactoring on the rendering code. I removed the table elements (\<table/>, \<tr/> and \<td/>) and replaced them all with div elements. In case of a table style, I just add the corresponding display styles (table, table-row and table-cell). This way you only need to maintain one html structure and one rendering code instead of two, which reduces complexity a bit.
The result should be the same. Would be nice, if you could test, that you can achieve the same output for you as before.
I also removed the nameShort because I think it's redundant. You never show name and nameShort at the same time. So why maintain something, thats never used? If you want to use style table_* with short text, just use a short text as name. If you want to use style lines with a longer text, just put a longer text as name. And I think, you don't switch the styles so often...
But we can discuss this. If you have a use case, where you need both name and nameShort, you can convince me of the opposite.
Last but not least I like the font awesome icons very much. Great idea.

Anyway, thank you for the nice features and additions!
Sorry it took so long to review them.

Best regards
Sebastian

**Comment by spitzlbergerj** [comment]
Hello, Sebastian,
thanks for the information in your mail. With this I could restore the layout of my version completely. Great. If now the code is also simpler, then so much the better.

In JavaScript I am still a complete beginner. Studying computer science helps, but the details are left to the professionals. For that I do too little with it.

Awesome font has a large number of free icons. Unfortunately, some of the icons you need (e.g. washing machine/washer) are only available in the Pro version. But the download possibility is there and the module can handle URLs ;-)

So thank you very much for accepting the new changes. And maybe I will think of something again.

I just built a module for my Tesla: [MMM-TeslaLogger](https://github.com/spitzlbergerj/MMM-TeslaLogger) and just now I have extended it again. Also there better JavaScript knowledge would be worth its weight in gold ...

And tomorrow I'll try to extend the standard module currentweather with MQTT telegrams from my own weather station.

Many greetings
Sepp

**Pull request merged**
